### ISSUE TITLE
Gym not defined 

### ISSUE THREAD

**Issue by MayKali** [eleurent/obstacle-env#1]
Hello, I've followed your instructions here, but whenever I try to run the program it gives the following error:

Traceback (most recent call last):
  File "C:\Users\MayKali\Desktop\Test.py", line 1, in <module>
    env = gym.make("obstacle-v0")
NameError: name 'gym' is not defined

**Comment by eleurent** [comment]
Hello, 
Indeed, you should import the gym module first.
`import gym`

I'll add it to the example, thanks.
