### ISSUE TITLE
How to generate and visualize boundary?

### ISSUE THREAD

**Issue by GPrathap** [eleurent/obstacle-env#2]
![obstacle-env](https://user-images.githubusercontent.com/7587302/109220673-4c2c4180-77ca-11eb-89c6-eaa0ec84b462.gif)

How have you generated these boundaries that surround the current position of the vehicle? Could you share the corresponding APIs?

**Comment by eleurent** [comment]
Hi @GPrathap,
These boundaries are computed here: https://github.com/eleurent/obstacle-env/blob/master/obstacle_env/scene.py#L61

The circle around the system are divided into a finite number of sectors, and in each sector we compute the distance to each obstacle in the scene.
I used to consider the center of each angular sector to compute intersections with obstacles, which explains why they sometimes overlap in this previous video, as if half of the obstacle was not seen.
I just fixed that by considering the sides of the angular sector instead.

**Comment by GPrathap** [comment]
Thank you
